source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'DemoVideoPlaybackKit' do
	pod 'RxSwift' 
	pod 'RxCocoa'
	pod 'SnapKit'
	pod 'VideoPlaybackKit', :git => 'https://github.com/ustwo/videoplayback-ios' 
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
